### ISSUE TITLE
unable to boot rock64 on librecomputers renegade

### ISSUE THREAD

**Issue by ilovethensa** [Mic92/nixos-aarch64-images#18]
I built it, and flashed to the microSD card with the commands provided in the README but it doesnt boot, it works with armbian, there are two solid green and red lights but no video output

**Comment by pf0** [comment]
Same here... even tried to follow https://wiki.nixos.org/wiki/NixOS_on_ARM/PINE64_ROCK64.

**Comment by ilovethensa** [comment]
Yea i tried all sorts of stuff, i got it working once, but after a reboot it wouldnt boot anymore its really finicky this board

**Comment by Mic92** [comment]
Is this actually supposed to work with the same u-boot? It seems it's the same chipset but the whole connectivity on the board could be very different?

**Comment by pf0** [comment]
Sorry for adding the confusion I actually tried it with a Pine64 Rock64 board. Sadly, I could not manage to get it working.

**Comment by Mic92** [comment]
No idea. I don't have the board close to me. I used it quite a while ago.

**Comment by Mic92** [comment]
Pull requests are welcome. But I won't add hardware that i don't own, so closing this issue.
