### ISSUE TITLE
Unable to boot after update

### ISSUE THREAD

**Issue by thebitstick** [Mic92/nixos-aarch64-images#19]
I get a generic `RD image overlaps OS image` error during snapshot selection on boot and it gets kicked back out to U-Boot.

Can try to provide kernel version if relevant.

Any tips for recovery?

System: RockPro64

**Comment by Mic92** [comment]
I had the same issue recently. It's the old u-boot that has put a too low ram address into the persistent storage of u-boot.
Here is how I fixed it for rock64: https://wiki.nixos.org/wiki/NixOS_on_ARM/PINE64_ROCK64#Initrd_fails_to_unpack_during_boot

```
=== Initrd fails to unpack during boot ===

The old vendor U-Boot 2017.09 did not leave enough room between the kernel and initrd, causing recent kernels to overwrite the beginning of the initrd. This can be fixed by increasing <code>ramdisk_addr_r</code> in the U-Boot console, or using upstream U-Boot.

Here is how to achieve in the uboot console (hit enter during boot to access it):

<syntaxHighlight>
=> print ramdisk_addr_r # this prints the old value
ramdisk_addr_r=0x06000000
=> set ramdisk_addr_r 0x07000000 # this sets a new value
=> saveenv # this persist the the configuration
=> boot # than you can normally boot, if it still fails, you can try to increase the ramdisk_addr_r value further
</syntaxHighlight>
```

**Comment by Mic92** [comment]
Hopefully future installation no longer have this issue after: https://github.com/Mic92/nixos-aarch64-images/pull/16
