### ISSUE TITLE
Config and boot without uart

### ISSUE THREAD

**Issue by gnull** [Mic92/nixos-aarch64-images#23]
Hi!

Is it possible to somehow chroot into this image and run the initial setup? I was wondering if I can get it up and running without an UART cable, but maybe setting up ssh from the host machine and having rock64 boot with ssh the first time.

Ivan

**Comment by tleydxdy** [comment]
I think this would involve building a new sd image, I'm trying to figure out how to do that (doesn't seems to be hard, I'm just new to nix)
You can still use the HDMI+keyboard I guess. It is weird that at least for my Rock64 HDMI out is not working. I was able to get HDMI out on my board using archlinuxarm which I think just ships the mainline kernel, without any patches that look suspicious, so I'm wondering what's the difference between nixos's kernel config and their's to cause this difference.

**Comment by gnull** [comment]
I solved my problem by just buying an UART cable. So if it's too much
hassle, maybe it's not worth it, not critical.

Ivan

**Comment by tleydxdy** [comment]
btw, does HDMI works on your rock64 after install? just curious

**Comment by Mic92** [comment]
Unfortunately I have no control over the way this is build, so we would need to fix it in nixpkgs. What does /proc/cmdline says if you boot with uart? Ideally there should be console=tty0 and console=ttys0 in there. HDMI used to work for me with the rock64. However I only ever used it when I was still using their kernel fork. I don't have physical access to it just now.

**Comment by tleydxdy** [comment]
I think it might be nice if in addition to pulling the image from cache the script can also build the image locally, this way people can make modifications as needed (enable ssh/add kernel patch/etc).

**Comment by Mic92** [comment]
If you build the image yourself, why than use this project at all? Wouldn't be something like nixos-generate better in this case. It also would require a lot of cross-compilation that was avoided here.
