### ISSUE TITLE
Docs lacking on how to provide config, user/pass

### ISSUE THREAD

**Issue by keithy** [Mic92/nixos-aarch64-images#7]
Managed to build the image, and boot. ssh appears to be running.

Cant see from docs (?) where to provide a configuration, or whether a default user/pass is provided.

**Comment by Mic92** [comment]
Images are not rebuild but only their layout is adapted to the specific arm board to avoid cross-compilation hence it's not possible to provide custom nixos configuration. There is also no default password provided by the prebuild nixos images either but I don't see a way to fix this in this project itself. After dd you can mount the partition on a different machine to copy in an ssh key.

**Comment by keithy** [comment]
Thanks, at least I know what to do now.... and it works.
